from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("F:\\learn\\AI\\carr001\\learn_ai\\third_party\\ChatGLM-6b\\THUDM\\chatglm-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("F:\\learn\\AI\\carr001\\learn_ai\\third_party\\ChatGLM-6b\\THUDM\\chatglm-6b", trust_remote_code=True).half().cuda()
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
response, history = model.chat(tokenizer, "你好", history=[])
print(response)